language: objective-c
script:
- swift test
matrix:
  include:
  - osx_image: xcode9.2
  - osx_image: xcode9.1
  - osx_image: xcode9
env:
  global:
  - LANG=en_US.UTF-8
  - LC_ALL=en_US.UTF-8
branches:
  only:
  - master
