language: objective-c
osx_image: xcode9.2
install:
- eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
- swift package generate-xcodeproj
- xcodebuild test -scheme SwiftPowerAssert-Package -configuration $CONFIGURATION
  -sdk macosx -destination 'platform=OS X,arch=x86_64'
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - LANG=en_US.UTF-8
  - LC_ALL=en_US.UTF-8
  - TOOLCHAINS=org.swift.3020171208a
  matrix:
  - CONFIGURATION=Debug
  - CONFIGURATION=Release
branches:
  only:
  - master
